# Required:
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/denite.nvim'
if = 'has("nvim")'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'kballard/vim-fish'

[[plugins]]
repo = 'kien/rainbow_parentheses.vim'
hook_source = 'source ~/.config/nvim/rc/plugins/plugins-rainbow_parentheses.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_source = 'source ~/.config/nvim/rc/plugins/plugins-vim-airline.vim'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
