[[plugins]]
repo = 'Shougo/vimshell.vim'
hook_source = 'source ~/.config/nvim/rc/plugins/plugins-vimshell.vim'

[[plugins]]
repo = 'Shougo/unite.vim'
on_source = ['vimshell.vim']

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("nvim")'
hook_source = 'source ~/.config/nvim/rc/plugins/plugins-deoplete.vim'

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_source = ['deoplete.nvim']

[[plugins]]
repo = 'Shougo/neosnippet'
on_i = 1
depends = ['neosnippet-snippets']

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_source = 'source ~/.config/nvim/rc/plugins/plugins-nerdtree.vim'

[[plugins]]
repo = 'ryanoasis/vim-devicons'
on_source = ['nerdtree']
hook_source = 'source ~/.config/nvim/rc/plugins/plugins-vim-devicons.vim'

[[plugins]]
repo = 'tiagofumo/vim-nerdtree-syntax-highlight'
on_source = ['nerdtree']

[[plugins]]
repo = 'machakann/vim-sandwich'
on_i = 1
