# Required:
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/denite.nvim'
if = 'has("nvim")'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_source = 'source ~/.config/nvim/rc/plugins/plugins-nerdtree.vim'

[[plugins]]
repo = 'tiagofumo/vim-nerdtree-syntax-highlight'
on_source = ['nerdtree']

[[plugins]]
repo = 'ryanoasis/vim-devicons'
on_source = ['nerdtree']
hook_source = 'source ~/.config/nvim/rc/plugins/plugins-vim-devicons.vim'

[[plugins]]
repo = 'kien/rainbow_parentheses.vim'
hook_source = 'source ~/.config/nvim/rc/plugins/plugins-rainbow_parentheses.vim'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_source = 'source ~/.config/nvim/rc/plugins/plugins-vim-airline.vim'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
