# Required:
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/denite.nvim'
if = 'has("nvim")'

[[plugins]]
repo = 'roxma/nvim-yarp'
if = '!has("nvim") && has("python3")'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
if = '!has("nvim") && has("python3")'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'itchyny/landscape.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = 'source ~/.config/nvim/rc/plugins/plugins-nerdtree.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = 'source ~/.config/nvim/rc/plugins/plugins-vim-fugitive.vim'

[[plugins]]
repo = 'kien/rainbow_parentheses.vim'
hook_add = 'source ~/.config/nvim/rc/plugins/plugins-rainbow_parentheses.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'source ~/.config/nvim/rc/plugins/plugins-lightline.vim'

[[plugins]]
repo = 'ryanoasis/vim-devicons'
hook_add = 'source ~/.config/nvim/rc/plugins/plugins-vim-devicons.vim'

[[plugins]]
repo = 'tiagofumo/vim-nerdtree-syntax-highlight'
