[[plugins]]
repo        = 'Shougo/unite.vim'
on_source   = ['vimshell.vim']

[[plugins]] 
repo        = 'davidhalter/jedi-vim'
on_ft       = 'python'

[[plugins]]
repo        = 'Shougo/deoplete.nvim'
if          = 'has("nvim") && has("python3")'
on_i        = 1
hook_source = 'source ~/.config/nvim/rc/plugins/plugins-deoplete.vim'

[[plugins]]
repo        = 'zchee/deoplete-jedi'
on_source   = ['deoplete.nvim']

[[plugins]]
repo        = 'Shougo/deol.nvim'
on_cmd      = 'Deol'
on_source   = 'denite.nvim'
hook_source    = '''
  nnoremap <Space>n :call deol#new({'command': 'fish'})<Cr>
  nnoremap <Space>d :Deol<Cr>
'''

[[plugins]]
repo      = 'Shougo/neosnippet'
depends   = ['neosnippet-snippets']
on_i      = 1
hook_source  = 'source ~/.config/nvim/rc/plugins/plugins-neosnippet.vim'

[[plugins]]
repo        = 'cespare/vim-toml'
on_ft       = 'toml'

[[plugins]]
repo        = 'kballard/vim-fish'
on_ft       = 'fish'

[[plugins]]
repo        = 'vim-python/python-syntax'
on_ft       = 'python'

[[plugins]]
repo        = 'tpope/vim-markdown'
on_ft       = 'markdown'
hook_source = 'source ~/.config/nvim/rc/plugins/plugins-markdown.vim'
